### ISSUE TITLE
Following

### ISSUE THREAD

**Issue by openai1998** [prinsss/export-twitter-following-list#3]
"Following seems to only retrieve 50 records now. How can I get more?"

**Comment by prinsss** [comment]
Hi,

Have you tried scroll down the page? You need to manually scroll down the list on the following page to make sure that Twitter web app loads all the data. We can't automatically retrieve all data since we do not actively send API requests.

If it doesn't work, please take a screnshot of the floating panel with runtime logs included.

P.S. There is a revamped version of this script, which has much more features. Give it a try! >> [twitter-web-exporter](https://github.com/prinsss/twitter-web-exporter)

**Comment by openai1998** [comment]
Currently, in the web version of Twitter, there are restrictions on display. Only 50 profiles are shown for both 'Following' and 'Followers.' How can I access more data?
It seems that even scrolling further only allows access to 50 profiles.
![Snipaste_2024-01-15_14-32-11](https://github.com/prinsss/export-twitter-following-list/assets/151999189/b28c10ac-344e-489a-a54f-e1c244faf448)
"Now we can see that only 50 entries are displayed in the web UI, and scrolling down doesn't reveal more. How can we obtain more data in this situation?"
![List"](https://github.com/prinsss/export-twitter-following-list/assets/151999189/4f36b62c-059c-442e-8d79-19a71444f484)
![555](https://github.com/prinsss/export-twitter-following-list/assets/151999189/55b1639d-e90d-4ddf-81e7-f5e3d1de21ad)

We returned to Twitter-web-exporter and found that only 50 pieces of data were obtained.
![app](https://github.com/prinsss/export-twitter-following-list/assets/151999189/1541d67b-1284-454a-8577-c8c434ba9ac9)

**Comment by prinsss** [comment]
Okay... I've reproduced this issue on my machine.

It seems that Twitter/X has some restrictions now, showing just a handful of accounts in the following tab. There are also some reports on the internet about this issue:

[Twitter seems to only be showing a select handful of accounts on my following tab. This happening for anyone else? : r/Twitter](https://www.reddit.com/r/Twitter/comments/137swd8/twitter_seems_to_only_be_showing_a_select_handful/)

[Unable to see full list of following and followers beside my accounts : r/Twitter](https://www.reddit.com/r/Twitter/comments/14h4ujh/unable_to_see_full_list_of_following_and/)

I'm sorry, but I don't think there's anything I can do about this now. It's an issue on Twitter's side. :(
